#ifndef COMPOSANTSINSTALLATIONELECT_GLOBAL_H
#define COMPOSANTSINSTALLATIONELECT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(COMPOSANTSINSTALLATIONELECT_LIBRARY)
#  define COMPOSANTSINSTALLATIONELECTSHARED_EXPORT Q_DECL_EXPORT
#else
#  define COMPOSANTSINSTALLATIONELECTSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // COMPOSANTSINSTALLATIONELECT_GLOBAL_H
